### ISSUE TITLE
Kepengurusan Linux NF Periode 2021-2022

### ISSUE THREAD

**Issue by support-sttnf** [STT-Terpadu-Nurul-Fikri/Linux-NF#1]
1. Ketua: Ridho Hafidz
2. Wakil Ketua: Akbar Satrio
3. Sekertaris: Bambang Triatmaja,
4. Bendahara: Sahrul Romadhon, Muhammad Rifqi
5. Humas: Alfi Syahri, Hadyan Abdul Aziz

**Comment by saroortega** [comment]
sahrulromadhon1200@gmail.com

**Comment by ridhohafidz** [comment]
mridhohafidz12@gmail.com

**Comment by bambang-ti** [comment]
triatmajabambang375@gmail.com

**Comment by akbarsatrio** [comment]
akba20261ti@student.nurulfikri.ac.id

**Comment by saroortega** [comment]
sahr20154ti@student.nurulfikri.ac.id

**Comment by bambang-ti** [comment]
bamb20049ti@student.nurulfikri.ac.id

**Comment by muhrifqi17** [comment]
muha18055ti@student.nurulfikri.ac.id

**Comment by alfisyhari** [comment]
alfi20011ti@student.nurulfikri.ac.id

**Comment by slamets75** [comment]
@alfisyhari sampai terakhir sudah saya join ke Share Drive (IT Club - Linux NF) ya

**Comment by hadyanaa** [comment]
@muhrifqi17 hadyanaa@student.nurulfikri.ac.id

**Comment by slamets75** [comment]
@muhrifqi17 ok besok email yang didaftarkan saya masukan ke classroom AWS untuk kita trial ya

**Comment by slamets75** [comment]
Selamat atas terpilihnya kepengurusan Linux NF periode 2021/2022, semoga dengan adanya kepengurusan ini, grup Linux NF bisa semakin aktif dan menaungi member di dalamnya. #Amiin

![kepengurusan linux nf](https://user-images.githubusercontent.com/22762466/108588386-7bd2e800-738b-11eb-921b-5e21665e074e.jpg)

**Comment by bambang-ti** [comment]
Hasil rapat perdana kepengurusan Linux NF 20 Februari 2021 

1. Usulkan waktu untuk perkenalan Linux NF kepada member
2. Mulai kelas virtual dan workshop dengan narasumber dari pengurus, pembina atau dari alumni yang berkompeten
3. Untuk tema dari narasumber bisa di diskusikan dengan pengurus atau narasumber dibebaskan memilih tema
4. Mulai breakdown program kerja dimulai dari beginner, dan untuk yang expert bisa sambil berjalan
5. Untuk program go to school bisa kordinasi dengan IT club yang lain atau dengan penelitian/pengabdian masyarakat
6. Pembuatan rekam jejak atau dokumentasi setiap kegiatan Linux NF
